/**
 * WHAT: Human-readable help text for ledger-cli.
 * WHY: command syntax must be discoverable without requiring a readable workspace ledger.
 */
export function formatLedgerCliHelp(): string {
  return [
    'Usage: ledger-cli <command> [options]',
    '',
    'Commands:',
    '  help',
    '      Show this help text.',
    '',
    '  overview --ledger <file>',
    '      Print a compact card and relationship overview.',
    '',
    '  unanswered --ledger <file> [--json]',
    '      List threads whose latest meaningful note still needs an agent answer.',
    '',
    '  answer --ledger <file> --thread-id <id> (--message <text> | --message-file <file>)',
    '      Append a short agent answer to a thread content file.',
    '',
    '  mutate --ledger <file> [--mutation <file>] [--card-id <id>] [card options]',
    '      Persist targeted ledger edits.',
    '',
    '  export --ledger <file> --output <file.md>',
    '      Export a ledger to Markdown.',
    '',
    '  done --ledger <file> --card-id <id>',
    '  todo --ledger <file> --card-id <id>',
    '      Update a card status.',
    '',
    '  assets list-referenced --root <workspace> [--json] [--include-risky ui-mockups]',
    '      List managed media assets referenced by decision-os text state.',
    '',
    '  assets list-orphans --root <workspace> [--json] [--include-risky ui-mockups]',
    '      List managed media assets not referenced and not pinned.',
    '',
    '  assets gc --root <workspace> --dry-run',
    '  assets gc --root <workspace> --write-plan .decision-os/assets-gc-plan.json',
    '      Report or write a deletion plan for unreferenced media and unused decision-os text files from active state.json roots.',
    '      Git-ignored paths are excluded from GC plans.',
    '',
    '  assets apply-gc-plan --root <workspace> --plan .decision-os/assets-gc-plan.json',
    '      Delete exactly the files listed in a previously written asset GC plan.',
    '',
    '  assets prune-json --root <workspace> [--domain <name>] --dry-run',
    '  assets prune-json --root <workspace> [--domain <name>] --write',
    '      Remove stale imageSizes entries whose images are not present in Markdown.',
    '',
    '  assets stage-referenced --root <workspace> --domain <name> [--include-risky ui-mockups]',
    '      Git-stage decision-os text state and referenced managed media for a domain.',
    '',
    '  migrate-decision-os --root <workspace> [--dry-run] [--write] [--json] [--allow-dirty]',
    '      Rename a legacy workspace directory and rewrite decision-os storage refs.',
    '',
    'Common mutate options:',
    '  --card-title <title>',
    '  --card-comment <markdown>',
    '  --card-comment-file <file>',
    '  --card-labels <label-a,label-b>',
    '  --card-x <number> --card-y <number> --card-w <number> --card-h <number>',
    '  --add-card-file <file>',
    '  --remove-card <id>',
    '  --add-relationship <id:from:to:label>',
    '  --remove-relationship <id>',
    '',
    'Examples:',
    '  ledger-cli unanswered --ledger .decision-os/specs.json --json',
    '  ledger-cli answer --ledger .decision-os/specs.json --thread-id thread-card-a --message "Implemented."',
    '  ledger-cli answer --ledger .decision-os/specs.json --thread-id thread-card-a --message-file /tmp/answer.md',
    '  ledger-cli assets gc --root /path/to/workspace --write-plan .decision-os/assets-gc-plan.json',
    '  ledger-cli assets apply-gc-plan --root /path/to/workspace --plan .decision-os/assets-gc-plan.json',
    '  ledger-cli migrate-decision-os --root /path/to/workspace --dry-run',
    '  ledger-cli migrate-decision-os --root /path/to/workspace --write',
  ].join('\n');
}
