/**
 * WHAT: Human-readable help text for ledger-cli.
 * WHY: command syntax must be discoverable without requiring a readable workspace ledger.
 */
export function formatLedgerCliHelp(): string {
  return [
    'Usage: ledger-cli <command> [options]',
    '',
    'Commands:',
    '  projects',
    '      List available project ids and names.',
    '',
    '  master-task-create --project <project-id> --title <title> [--subtask <title>]...',
    '      Create one Tasks master card and its subtasks, then print their Markdown file paths.',
    '',
    '  queue-skill --skill <name> --model <model> --effort <effort>',
    '      Queue one skill after the current execution, then run the calling skill again in a fresh context.',
    '',
    '  help',
    '      Show this help text.',
    '',
    '  overview --ledger <file>',
    '      Print a compact card and relationship overview.',
    '',
    '  card-context --ledger <file> --card-id <id> --json',
    '      Print full card metadata, content file paths, relationships, and owning zone.',
    '',
    '  card-read --card-id <id> [--card-id <id>]...',
    '      Discover and print the bodies and full threads for one to 30 cards as Markdown.',
    '',
    '  prompt query --name <name> [--name <name>]...',
    '      Print server-owned pipeline prompts verbatim in argument order.',
    '',
    '  session-context --ledger <file> --card-id <id> --json',
    '      Print the target card, thread, zone, direct links, linked statuses, and lifecycle validation.',
    '',
    '  master-task-gate --ledger <file> --card-id <id> --json',
    '      Print one closeout decision with every linked-card discrepancy.',
    '',
    '  master-task-complete --card-id <id> [--ledger <file>]',
    '      Complete and Git-commit one master task through the running Decision OS server.',
    '      Uses DECISION_OS_LEDGER_FILE, DECISION_OS_SERVER_URL, and DECISION_OS_PROJECT_ID from the skill runtime.',
    '',
    '  master-task-apply --ledger <file> --plan-stdin',
    '      Apply a JSON master-task plan through scoped task commands and generate every card and relationship id.',
    '      Input: {"masterCardId":"card-id","title":"Title","zoneTitle":"Zone","sections":[{"title":"Finding","markdown":"1. **State:** ..."}],"subtasks":[{"title":"Task","sections":[{"title":"Scope","markdown":"1. **Objective:** ..."}]}]}',
    '      The existing lifecycle header, timestamps, and geometry are preserved.',
    '',
    '  master-task-progress --ledger <file> --plan-stdin --json',
    '      Update master/subtask content and labels through scoped task commands, append one reply, and return the gate.',
    '      Input: {"masterCardId":"card-id","updates":[{"cardId":"card-id","sections":[{"title":"Result","markdown":"1. **State:** ..."}]}],"verifiedSubtaskIds":["card-id"],"reply":"Agent reply."}',
    '      This command cannot complete the master task.',
    '',
    '  execution-profile --ledger <file> --json',
    '      Print project-scoped commands and server policy.',
    '',
    '  codex-run-audit --root <catalog-root> --count <n> [--cutoff <epoch-ms>] [--exclude <run-id>]',
    '      Audit the newest runs across every catalog project with latency when telemetry exists.',
    '',
    '  codex-run-events --run-id <id> --item-type <type> [--limit <n>] [--root <catalog-root>]',
    '      Return only the requested normalized events from one catalog-owned Codex run.',
    '',
    '  zone-cards --ledger <file> --zone-id <id> --json',
    '      Print cards owned by a zone with ids, titles, statuses, geometry, and content file paths.',
    '',
    '  unanswered --ledger <file> [--json]',
    '      List threads whose latest meaningful note still needs an agent answer.',
    '',
    '  validate-master-tasks --ledger <file> [--card-id <id>]',
    '      Validate one scoped JSON master-task contract, or every master task when no card id is supplied.',
    '',
    '  answer --ledger <file> --thread-id <id> (--message <text> | --message-file <file> | --message-stdin)',
    '      Append a short agent answer to a thread content file.',
    '',
    '  mutate --ledger <file> [--mutation <file>] [--card-id <id>] [card options]',
    '      Persist targeted ledger edits.',
    '      Use --card-questionnaires-file <file> to replace one card\'s versioned questionnaire map.',
    '',
    '  export --ledger <file> --output <file.md>',
    '      Export a ledger to Markdown.',
    '',
    '  done --ledger <file> --card-id <id>',
    '  todo --ledger <file> --card-id <id>',
    '      Update a card status.',
    '',
    '  skills create --source <skill-directory> [--json]',
    '  skills update --source <skill-directory> [--json]',
    '      Synchronize an OpenAI-format skill with the current server root and commit it.',
    '',
    '  assets list-referenced --root <workspace> [--json] [--include-risky ui-mockups]',
    '      List managed media assets referenced by decision-os text state.',
    '',
    '  assets list-orphans --root <workspace> [--json] [--include-risky ui-mockups]',
    '      List managed media assets not referenced and not pinned.',
    '',
    '  assets gc --root <workspace> --dry-run',
    '  assets gc --root <workspace> --write-plan .decision-os/assets-gc-plan.json',
    '      Report or write a deletion plan for unreferenced media and unused decision-os text files from active state.json roots.',
    '      Git-ignored paths are excluded from GC plans.',
    '',
    '  assets apply-gc-plan --root <workspace> --plan .decision-os/assets-gc-plan.json',
    '      Delete exactly the files listed in a previously written asset GC plan.',
    '',
    '  assets prune-json --root <workspace> [--domain <name>] --dry-run',
    '  assets prune-json --root <workspace> [--domain <name>] --write',
    '      Remove stale imageSizes entries whose images are not present in Markdown.',
    '',
    '  assets stage-referenced --root <workspace> --domain <name> [--include-risky ui-mockups]',
    '      Git-stage decision-os text state and referenced managed media for a domain.',
    '',
    '  migrate-decision-os --root <workspace> [--dry-run] [--write] [--json] [--allow-dirty]',
    '      Rename a legacy workspace directory and rewrite decision-os storage refs.',
    '',
    '  migrate-master-tasks --source-ledger <file> --target-ledger <file> [--write] [--json]',
    '      Move every master-task zone and its relationship-backed task graph into the canonical tasks ledger.',
    '',
    'Common mutate options:',
    '  --card-title <title>',
    '  --card-comment <markdown>',
    '  --card-comment-file <file>',
    '  --append <fact>                 Append one fact; repeat for multiple facts.',
    '  --replace <fact>                Replace facts; repeat for the complete next list.',
    '  --card-labels <label-a,label-b>',
    '  --card-x <number> --card-y <number> --card-w <number> --card-h <number>',
    '  --add-card-file <file>',
    '  --remove-card <id>',
    '  --add-relationship <id:from:to:label>',
    '  --remove-relationship <id>',
    '',
    'Examples:',
    '  ledger-cli unanswered --ledger .decision-os/specs.json --json',
    '  ledger-cli card-context --ledger .decision-os/specs.json --card-id card-a --json',
    '  ledger-cli card-read --card-id card-a --card-id card-b',
    '  ledger-cli zone-cards --ledger .decision-os/specs.json --zone-id zone-a --json',
    '  ledger-cli answer --ledger .decision-os/specs.json --thread-id thread-card-a --message "Implemented."',
    '  ledger-cli answer --ledger .decision-os/specs.json --thread-id thread-card-a --message-file /tmp/answer.md',
    '  ledger-cli assets gc --root /path/to/workspace --write-plan .decision-os/assets-gc-plan.json',
    '  ledger-cli assets apply-gc-plan --root /path/to/workspace --plan .decision-os/assets-gc-plan.json',
    '  ledger-cli migrate-decision-os --root /path/to/workspace --dry-run',
    '  ledger-cli migrate-decision-os --root /path/to/workspace --write',
  ].join('\n');
}
