import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const root = new URL('../../../', import.meta.url);

function source(path: string): string {
  return readFileSync(new URL(path, root), 'utf8');
}

test('card markdown images render as resizeable aspect-preserving media and adjacent images become a carousel', () => {
  const parser = source('frontend/src/runtime/ledger/helper/parse-ledger-card-markdown.ts');
  const inlineParser = source('frontend/src/runtime/ledger/helper/parse-ledger-markdown-inline.ts');
  const renderer = source('frontend/src/runtime/ledger/component/render-ledger-card-markdown.ts');
  const mediaRenderer = source('frontend/src/runtime/ledger/component/render-ledger-card-media.ts');
  const actionClick = source('frontend/src/runtime/input/controller/handle-action-click.ts');
  const keyboard = source('frontend/src/runtime/input/controller/handle-keyboard.ts');
  const deleteImageController = source('frontend/src/runtime/card/controller/delete-card-image-controller.ts');
  const mediaLayout = source('frontend/src/runtime/ledger/helper/sync-ledger-card-media-layout.ts');
  const mediaCarouselPersistence = source('frontend/src/runtime/ledger/helper/persist-ledger-card-media-carousel.ts');
  const titleRenderer = source('frontend/src/runtime/ledger/component/append-title-text.ts');
  const wheel = source('frontend/src/runtime/gesture/controller/handle-wheel.ts');
  const css = source('frontend/assets/canvas/objects.css');
  const imageViewer = source('frontend/src/runtime/ledger/effect/open-ledger-card-image-viewer.ts');
  const panzoom = source('frontend/assets/vendor/panzoom-4.6.2.es.js');
  const resizeInteraction = source('frontend/src/runtime/ledger/helper/bind-ledger-card-media-resize.ts');
  const surfaceRuntime = source('frontend/src/runtime/surface-runtime.ts');
  const interact = source('frontend/assets/vendor/interact-1.10.27.min.js');

  assert.match(inlineParser, /text\.startsWith\('!\[', start\)/);
  assert.match(inlineParser, /kind:\s*'image'/);
  assert.match(parser, /kind:\s*'images'/);
  assert.match(parser, /standaloneImagesFromLine/);
  assert.match(parser, /if \(!line\) \{\s*list = null;\s*continue;\s*\}/);
  assert.match(parser, /images\.images\.push\(\.\.\.standaloneImages\)/);
  assert.match(renderer, /renderLedgerCardMedia/);
  assert.match(mediaRenderer, /ledger-card-media-carousel/);
  assert.match(mediaRenderer, /renderFullscreenButton/);
  assert.match(mediaRenderer, /is-fullscreen-control-visible/);
  assert.match(mediaRenderer, /openLedgerCardImageViewer\(\{ alt: image\.alt, source: projectScopedRequestPath\(image\.src\), trigger: button \}\)/);
  assert.match(imageViewer, /assets\/vendor\/panzoom-4\.6\.2\.es\.js/);
  assert.match(imageViewer, /minScale:\s*0\.3/);
  assert.match(imageViewer, /maxScale:\s*50/);
  assert.match(imageViewer, /startScale:\s*1/);
  assert.match(imageViewer, /panzoom\.zoomWithWheel\(event\)/);
  assert.match(imageViewer, /panzoom\.destroy\(\)/);
  assert.match(panzoom, /onPointer\('move', document, handleMove/);
  assert.doesNotMatch(imageViewer, /dialog\.addEventListener\('pointer(move|up)'[\s\S]*stopPropagation/);
  assert.match(imageViewer, /trigger\.focus\(\)/);
  assert.match(imageViewer, /document\.body\.style\.overflow = 'hidden'/);
  assert.match(imageViewer, /trapDialogFocus\(event, dialog\)/);
  assert.match(css, /\.ledger-card-media-fullscreen\s*\{[^}]*opacity:\s*0;[^}]*pointer-events:\s*none;/s);
  assert.match(css, /\.ledger-card-media-slide\.is-fullscreen-control-visible \.ledger-card-media-fullscreen[^{]*\{[^}]*opacity:\s*1;[^}]*pointer-events:\s*auto;/s);
  assert.match(css, /\.ledger-card-image-viewer-close\s*\{[^}]*position:\s*fixed;[^}]*top:\s*max\(16px, env\(safe-area-inset-top\)\);[^}]*right:\s*max\(16px, env\(safe-area-inset-right\)\);/s);
  assert.doesNotMatch(mediaRenderer, /ledger-card-image-shell/);
  assert.match(mediaRenderer, /function imageTitleFromSource\(source: string\)/);
  assert.match(mediaRenderer, /decodeURIComponent\(filename\)/);
  assert.match(mediaRenderer, /const titleText = imageTitleFromSource\(image\.src\)\.trim\(\)/);
  assert.match(mediaRenderer, /document\.createElement\('figcaption'\)/);
  assert.match(mediaRenderer, /ledger-card-media-title/);
  assert.match(mediaRenderer, /ledger-card-media-delete/);
  assert.match(mediaRenderer, /dataset\.action = 'confirm-delete-card-image'/);
  assert.match(mediaRenderer, /function updateMediaDeleteButton/);
  assert.match(mediaRenderer, /button\.dataset\.imageSrc = image\.src/);
  assert.match(mediaRenderer, /button\.dataset\.carouselSlideIndex = String\(index\)/);
  assert.match(mediaRenderer, /button\.dataset\.carouselSources = JSON\.stringify\(images\.map/);
  assert.match(mediaRenderer, /deleteButton\.addEventListener\('click', \(\) => \{\s*updateMediaDeleteButton\(deleteButton, block\.images, track\);\s*\}\)/);
  assert.match(mediaRenderer, /nav\.replaceChildren\(previous, next, \.\.\.\(deleteButton \? \[deleteButton\] : \[\]\)\)/);
  assert.match(mediaRenderer, /ledger-card-media-slide-nav/);
  assert.match(mediaRenderer, /ledger-card-media-slide-button/);
  assert.match(mediaRenderer, /button\.dataset\.slideIndex = String\(index\)/);
  assert.match(mediaRenderer, /button\.classList\.toggle\('is-active', active\)/);
  assert.match(mediaRenderer, /button\.setAttribute\('aria-current', active \? 'true' : 'false'\)/);
  assert.match(mediaRenderer, /scrollCarouselTo\(shell, images, track, index, stateId, 'auto'\)/);
  assert.match(actionClick, /confirmCardImageDeletionController/);
  assert.match(actionClick, /deleteCardImageController/);
  assert.match(actionClick, /carouselSources: actionTarget\.dataset\.carouselSources/);
  assert.match(actionClick, /carouselSlideIndex: actionTarget\.dataset\.carouselSlideIndex/);
  assert.match(deleteImageController, /clearCanvasMediaOverlay\(\{ reconcilePromotedGeometry: false \}\)/);
  assert.match(deleteImageController, /persistLedgerCardMediaCarouselDeleteHandoff/);
  assert.match(deleteImageController, /sources: parseCarouselSources\(input\.carouselSources\)/);
  assert.match(deleteImageController, /slideIndex: Number\(input\.carouselSlideIndex\)/);
  assert.match(deleteImageController, /commitActiveLedgerMutation\(\{ action: 'delete-card-image', cardId, imageSrc \}, \{ render: true \}\)/);
  assert.match(keyboard, /modal\.dataset\.confirmKind === 'card-image'/);
  assert.match(keyboard, /carouselSources: modal\.dataset\.carouselSources/);
  assert.match(keyboard, /carouselSlideIndex: modal\.dataset\.carouselSlideIndex/);
  assert.match(mediaRenderer, /ledgerCardMediaCarouselStateId/);
  assert.match(mediaRenderer, /readLedgerCardMediaCarouselSlide/);
  assert.match(mediaRenderer, /saveLedgerCardMediaCarouselSlide/);
  assert.match(mediaRenderer, /hydrateCarouselSlide\(shell, persistedCarouselStateId, block\.images\)/);
  assert.match(mediaRenderer, /dataset\.wheelCapture = 'true'/);
  assert.match(mediaRenderer, /dataset\.imageSizeId = sizeSource/);
  assert.match(mediaRenderer, /--ledger-card-media-aspect-ratio/);
  assert.match(mediaRenderer, /const sizeSource = block\.images\[0\]\?\.src \?\? ''/);
  assert.match(mediaRenderer, /if \(index === 0\)[\s\S]*applyImageAspectRatio\(shell, element\)/);
  assert.match(mediaLayout, /--ledger-card-media-contained-width/);
  assert.match(mediaLayout, /--ledger-card-media-contained-height/);
  assert.match(mediaRenderer, /syncCarouselSlider/);
  assert.match(mediaLayout, /--ledger-card-media-slider-thumb-width/);
  assert.match(mediaLayout, /--ledger-card-media-slider-thumb-left/);
  assert.match(mediaRenderer, /ledger-card-media-progress/);
  assert.match(mediaRenderer, /ledger-card-media-progress-thumb/);
  assert.match(mediaLayout, /shell\.querySelector\('\.ledger-card-media-track'\)/);
  assert.match(mediaLayout, /const width = imageRatio > frameRatio \? frameWidth : frameHeight \* imageRatio/);
  assert.match(mediaLayout, /const height = imageRatio > frameRatio \? frameWidth \/ imageRatio : frameHeight/);
  assert.match(mediaLayout, /const slidePaddingBottom = slide \? Number\.parseFloat\(getComputedStyle\(slide\)\.paddingBottom\) \|\| 0 : 0/);
  assert.match(mediaLayout, /rawFrameHeight - titleHeight - slidePaddingBottom/);
  assert.match(mediaLayout, /naturalWidth/);
  assert.match(mediaRenderer, /imageSizes\[source\] = \{ width, height \}/);
  assert.match(mediaRenderer, /card\.imageSizes = imageSizes/);
  assert.match(mediaRenderer, /if \(committed \|\| pendingResizeRevisions\.get\(element\) !== revision\) return/);
  assert.match(mediaRenderer, /current\.imageSizes = previousImageSizes/);
  assert.match(mediaRenderer, /restoreConfirmedImageResize\(element, previousImageSizes\[source\] \?\? \{\}\)/);
  assert.match(mediaRenderer, /ledger-card-media-resize-commit/);
  assert.match(mediaRenderer, /aria-label', 'Resize carousel/);
  assert.match(resizeInteraction, /globalThis\.interact\(handleSelector\)\.draggable/);
  assert.match(resizeInteraction, /inputScale: promoted \? renderedWidthScale : transformedScale\(shell\)/);
  assert.match(resizeInteraction, /shell\.style\.width = `\$\{Math\.round\(resize\.localWidth \* resize\.renderedWidthScale\)\}px`/);
  assert.match(surfaceRuntime, /interact-1\.10\.27\.min\.js/);
  assert.match(interact, /interact/);
  assert.match(mediaRenderer, /dataset\.mediaPromotionScale/);
  assert.match(mediaRenderer, /Math\.round\(element\.offsetWidth \/ dimensionScale\)/);
  assert.match(mediaRenderer, /Math\.round\(element\.offsetHeight \/ dimensionScale\)/);
  assert.doesNotMatch(mediaRenderer, /getBoundingClientRect\(\)\.(width|height)/);
  assert.match(mediaRenderer, /sendActiveLedgerMutation\(\{ action: 'patch-card', cardPatch: \{ id: options\.cardId/);
  assert.match(mediaRenderer, /const slideCount = track\.children\.length/);
  assert.match(mediaRenderer, /const nextIndex = \(currentIndex \+ direction \+ slideCount\) % slideCount/);
  assert.match(mediaRenderer, /saveLedgerCardMediaCarouselSlide\(stateId, nextIndex, slideCount\)/);
  assert.match(mediaRenderer, /function hasMeasuredCarouselTrack\(track: HTMLElement\): boolean/);
  assert.match(mediaRenderer, /if \(!track \|\| !hasMeasuredCarouselTrack\(track\)\) return;/);
  assert.match(mediaRenderer, /if \(track && !hasMeasuredCarouselTrack\(track\) && attempts < 6\)/);
  assert.match(mediaRenderer, /syncMediaCarousel\(shell, block\.images, track, persistedCarouselStateId\)/);
  assert.match(mediaRenderer, /syncMediaCarousel\(shell, block\.images, track, persistedCarouselStateId, \{ persist: false \}\)/);
  assert.match(mediaRenderer, /track\.scrollTo\(\{ left: nextIndex \* slideWidth, behavior \}\)/);
  assert.match(mediaRenderer, /function bindSingleSlideSwipe/);
  assert.match(mediaRenderer, /options\.carouselDriver === 'external'/);
  assert.match(mediaRenderer, /if \(!externalCarouselDriver\) bindSingleSlideSwipe/);
  assert.match(mediaRenderer, /dataset\.carouselStateId = persistedCarouselStateId/);
  assert.match(mediaRenderer, /dataset\.carouselStartIndex = String\(readLedgerCardMediaCarouselSlide/);
  assert.match(mediaRenderer, /Math\.max\(48, track\.clientWidth \* 0\.18\)/);
  assert.match(mediaRenderer, /current\.startIndex \+ direction/);
  assert.match(mediaRenderer, /previous\.textContent = '‹'/);
  assert.match(mediaRenderer, /next\.textContent = '›'/);
  assert.match(mediaCarouselPersistence, /storageKey = 'decision-os\.cardMedia\.carouselSlides'/);
  assert.match(mediaCarouselPersistence, /localStorage\.getItem\(storageKey\)/);
  assert.match(mediaCarouselPersistence, /localStorage\.setItem\(storageKey, JSON\.stringify\(states\)\)/);
  assert.match(mediaCarouselPersistence, /export function ledgerCardMediaCarouselStateId/);
  assert.match(mediaCarouselPersistence, /export function persistLedgerCardMediaCarouselDeleteHandoff/);
  assert.match(mediaCarouselPersistence, /const nextSources = sources\.filter/);
  assert.match(mediaCarouselPersistence, /saveLedgerCardMediaCarouselSlide\(stateId, options\.slideIndex, nextSources\.length\)/);
  assert.match(renderer, /renderLedgerCardMarkdown\(markdown: string, options/);
  assert.match(wheel, /advanceCarouselFromWheel\(event\)/);
  assert.match(wheel, /event\.ctrlKey/);
  assert.match(wheel, /\.ledger-card-media-carousel/);
  assert.match(wheel, /event\.preventDefault\(\)/);
  assert.match(wheel, /track\.scrollTo\(\{ left: nextIndex \* slideWidth, behavior: 'smooth' \}\)/);
  assert.match(wheel, /card-image-carousel-wheel/);
  assert.match(titleRenderer, /node\.kind === 'image'/);
  assert.match(source('frontend/src/runtime/ledger/component/append-inline-nodes.ts'), /Math\.round\(frame\.offsetWidth\)/);
  assert.doesNotMatch(source('frontend/src/runtime/ledger/component/append-inline-nodes.ts'), /getBoundingClientRect\(\)\.(width|height)/);
  assert.match(css, /\.ledger-card-media-shell\s*{[^}]*--ledger-card-media-slider-row-height:\s*7px;[^}]*--ledger-card-media-slide-nav-height:\s*22px;[^}]*--ledger-card-media-title-row-min-height:\s*22px;[^}]*--ledger-card-media-title-slider-gap:\s*6px;[^}]*--ledger-card-media-bottom-inset:\s*8px;[^}]*max-width:\s*100%;[^}]*aspect-ratio:\s*var\(--ledger-card-media-aspect-ratio, 4 \/ 3\);[^}]*resize:\s*horizontal;/s);
  assert.match(css, /\.ledger-card-media-resize-handle\s*{[^}]*width:\s*28px;[^}]*height:\s*28px;[^}]*cursor:\s*ew-resize;[^}]*touch-action:\s*none;/s);
  assert.match(css, /\.ledger-card-media-resize-handle::before\s*{[^}]*width:\s*16px;[^}]*height:\s*16px;[^}]*border:[^}]*content:\s*"";[^}]*background:[^}]*box-shadow:/s);
  assert.match(css, /\.ledger-card-media-resize-handle:hover::before,[\s\S]*\.ledger-card-media-resize-handle:focus-visible::before\s*{/);
  assert.match(css, /\.ledger-card-media-track\s*{[^}]*scroll-snap-type:\s*x mandatory;/s);
  assert.match(css, /\.ledger-card-media-carousel \.ledger-card-media-track\s*{[^}]*scrollbar-width:\s*none;/s);
  assert.match(css, /\.ledger-card-media-carousel \.ledger-card-media-track\s*{[^}]*touch-action:\s*pan-y;/s);
  assert.match(css, /\.ledger-card-media-slide\s*{[^}]*grid-template-rows:\s*minmax\(0, 1fr\) auto;[^}]*padding:[^}]*var\(--ledger-card-media-slide-nav-height\)[^}]*var\(--ledger-card-media-title-slider-gap\)/s);
  assert.match(css, /\.ledger-card-media-image\s*{[^}]*width:\s*var\(--ledger-card-media-contained-width, auto\);[^}]*height:\s*var\(--ledger-card-media-contained-height, auto\);[^}]*max-width:\s*100%;[^}]*max-height:\s*100%;[^}]*object-fit:\s*contain;[^}]*object-position:\s*center;/s);
  assert.match(css, /\.ledger-card-media-nav \.ledger-card-media-delete\s*{[^}]*position:\s*absolute;[^}]*top:\s*8px;[^}]*right:\s*10px;[^}]*width:\s*24px;[^}]*height:\s*24px;[^}]*opacity:\s*1;/s);
  assert.match(css, /\.ledger-card-media-nav \.ledger-card-media-delete::after\s*{[^}]*display:\s*none;/s);
  assert.doesNotMatch(css, /\.ledger-card-media-shell:hover \.ledger-card-media-delete/);
  assert.match(css, /\.ledger-card-media-title\s*{[^}]*display:\s*block;[^}]*width:\s*100%;[^}]*min-height:\s*var\(--ledger-card-media-title-row-min-height\);[^}]*overflow-wrap:\s*anywhere;/s);
  assert.doesNotMatch(css, /\.ledger-card-media-shell:hover \.ledger-card-media-title/);
  assert.match(css, /\.ledger-card-media-progress\s*{[^}]*right:\s*28px;[^}]*bottom:\s*var\(--ledger-card-media-bottom-inset, 8px\);[^}]*left:\s*8px;/s);
  assert.match(css, /\.ledger-card-media-progress-thumb\s*{[^}]*left:\s*var\(--ledger-card-media-slider-thumb-left, 0%\);[^}]*width:\s*var\(--ledger-card-media-slider-thumb-width, 100%\);/s);
  assert.match(css, /\.ledger-card-media-slide-nav\s*{[^}]*bottom:\s*calc\([^}]*var\(--ledger-card-media-slider-row-height, 7px\)[^}]*\);[^}]*overflow-x:\s*auto;/s);
  assert.match(css, /\.ledger-card-media-slide-button\s*{[^}]*width:\s*20px;[^}]*font-variant-numeric:\s*tabular-nums;/s);
  assert.match(css, /\.ledger-card-media-slide-button:hover,[\s\S]*\.ledger-card-media-slide-button:focus-visible,[\s\S]*\.ledger-card-media-slide-button\.is-active\s*{/);
  assert.match(css, /\.ledger-card-media-nav\s*{[^}]*top:\s*6px;[^}]*bottom:\s*calc\([^}]*var\(--ledger-card-media-slide-nav-height, 22px\)[^}]*var\(--ledger-card-media-title-row-min-height, 22px\)[^}]*\);/s);
  assert.match(css, /\.ledger-card-inline-image-frame\s*{[^}]*aspect-ratio:\s*var\(--ledger-card-inline-image-aspect-ratio, 3 \/ 2\);[^}]*resize:\s*horizontal;/s);
  assert.match(css, /\.ledger-card-inline-image\s*{[^}]*object-fit:\s*contain;/s);
});
