import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const root = new URL('../../../', import.meta.url);

function source(path: string): string {
  return readFileSync(new URL(path, root), 'utf8');
}

test('card markdown images render as resizeable aspect-preserving media and adjacent images become a carousel', () => {
  const parser = source('frontend/src/runtime/ledger/helper/parse-ledger-card-markdown.ts');
  const inlineParser = source('frontend/src/runtime/ledger/helper/parse-ledger-markdown-inline.ts');
  const renderer = source('frontend/src/runtime/ledger/component/render-ledger-card-markdown.ts');
  const mediaRenderer = source('frontend/src/runtime/ledger/component/render-ledger-card-media.ts');
  const mediaLayout = source('frontend/src/runtime/ledger/helper/sync-ledger-card-media-layout.ts');
  const mediaCarouselPersistence = source('frontend/src/runtime/ledger/helper/persist-ledger-card-media-carousel.ts');
  const titleRenderer = source('frontend/src/runtime/ledger/component/append-title-text.ts');
  const doubleClick = source('frontend/src/runtime/input/controller/handle-card-double-click.ts');
  const wheel = source('frontend/src/runtime/gesture/controller/handle-wheel.ts');
  const css = source('frontend/assets/canvas/objects.css');

  assert.match(inlineParser, /text\.startsWith\('!\[', start\)/);
  assert.match(inlineParser, /kind:\s*'image'/);
  assert.match(parser, /kind:\s*'images'/);
  assert.match(parser, /standaloneImagesFromLine/);
  assert.match(parser, /if \(!line\) \{\s*list = null;\s*continue;\s*\}/);
  assert.match(parser, /images\.images\.push\(\.\.\.standaloneImages\)/);
  assert.match(renderer, /renderLedgerCardMedia/);
  assert.match(mediaRenderer, /ledger-card-media-carousel/);
  assert.match(mediaRenderer, /function imageTitleFromSource\(source: string\)/);
  assert.match(mediaRenderer, /decodeURIComponent\(filename\)/);
  assert.match(mediaRenderer, /const titleText = imageTitleFromSource\(image\.src\)\.trim\(\)/);
  assert.match(mediaRenderer, /document\.createElement\('figcaption'\)/);
  assert.match(mediaRenderer, /ledger-card-media-title/);
  assert.match(mediaRenderer, /ledgerCardMediaCarouselStateId/);
  assert.match(mediaRenderer, /readLedgerCardMediaCarouselSlide/);
  assert.match(mediaRenderer, /saveLedgerCardMediaCarouselSlide/);
  assert.match(mediaRenderer, /hydrateCarouselSlide\(shell, persistedCarouselStateId\)/);
  assert.match(mediaRenderer, /dataset\.wheelCapture = 'true'/);
  assert.match(mediaRenderer, /dataset\.imageSizeId = sizeSource/);
  assert.match(mediaRenderer, /--ledger-card-media-aspect-ratio/);
  assert.match(mediaRenderer, /const sizeSource = block\.images\[0\]\?\.src \?\? ''/);
  assert.match(mediaRenderer, /if \(index === 0\)[\s\S]*applyImageAspectRatio\(shell, element\)/);
  assert.match(mediaLayout, /--ledger-card-media-contained-width/);
  assert.match(mediaLayout, /--ledger-card-media-contained-height/);
  assert.match(mediaRenderer, /syncCarouselSlider/);
  assert.match(mediaLayout, /--ledger-card-media-slider-thumb-width/);
  assert.match(mediaLayout, /--ledger-card-media-slider-thumb-left/);
  assert.match(mediaRenderer, /ledger-card-media-progress/);
  assert.match(mediaRenderer, /ledger-card-media-progress-thumb/);
  assert.match(mediaLayout, /shell\.querySelector\('\.ledger-card-media-track'\)/);
  assert.match(mediaLayout, /const width = imageRatio > frameRatio \? frameWidth : frameHeight \* imageRatio/);
  assert.match(mediaLayout, /const height = imageRatio > frameRatio \? frameWidth \/ imageRatio : frameHeight/);
  assert.match(mediaLayout, /naturalWidth/);
  assert.match(mediaRenderer, /imageSizes\[source\] = \{ width, height \}/);
  assert.match(mediaRenderer, /dataset\.mediaPromotionScale/);
  assert.match(mediaRenderer, /Math\.round\(element\.offsetWidth \/ dimensionScale\)/);
  assert.match(mediaRenderer, /Math\.round\(element\.offsetHeight \/ dimensionScale\)/);
  assert.doesNotMatch(mediaRenderer, /getBoundingClientRect\(\)\.(width|height)/);
  assert.match(mediaRenderer, /commitActiveLedgerMutation\(\{ action: 'patch-card', cardPatch: \{ id: options\.cardId/);
  assert.match(mediaRenderer, /const slideCount = track\.children\.length/);
  assert.match(mediaRenderer, /const nextIndex = \(currentIndex \+ direction \+ slideCount\) % slideCount/);
  assert.match(mediaRenderer, /saveLedgerCardMediaCarouselSlide\(stateId, nextIndex, slideCount\)/);
  assert.match(mediaRenderer, /saveCurrentCarouselSlide\(shell, persistedCarouselStateId\)/);
  assert.match(mediaRenderer, /track\.scrollTo\(\{ left: nextIndex \* slideWidth, behavior: 'smooth' \}\)/);
  assert.match(mediaCarouselPersistence, /storageKey = 'corev2\.cardMedia\.carouselSlides'/);
  assert.match(mediaCarouselPersistence, /localStorage\.getItem\(storageKey\)/);
  assert.match(mediaCarouselPersistence, /localStorage\.setItem\(storageKey, JSON\.stringify\(states\)\)/);
  assert.match(mediaCarouselPersistence, /export function ledgerCardMediaCarouselStateId/);
  assert.match(renderer, /renderLedgerCardMarkdown\(markdown: string, options/);
  assert.match(doubleClick, /target\.closest\('\[data-ledger-card-media\]'\)/);
  assert.match(wheel, /advanceCarouselFromWheel\(event\)/);
  assert.match(wheel, /event\.ctrlKey/);
  assert.match(wheel, /\.ledger-card-media-carousel/);
  assert.match(wheel, /event\.preventDefault\(\)/);
  assert.match(wheel, /track\.scrollTo\(\{ left: nextIndex \* slideWidth, behavior: 'smooth' \}\)/);
  assert.match(titleRenderer, /node\.kind === 'image'/);
  assert.match(source('frontend/src/runtime/ledger/component/append-inline-nodes.ts'), /Math\.round\(frame\.offsetWidth\)/);
  assert.doesNotMatch(source('frontend/src/runtime/ledger/component/append-inline-nodes.ts'), /getBoundingClientRect\(\)\.(width|height)/);
  assert.match(css, /\.ledger-card-media-shell\s*{[^}]*max-width:\s*100%;[^}]*aspect-ratio:\s*var\(--ledger-card-media-aspect-ratio, 4 \/ 3\);[^}]*resize:\s*horizontal;/s);
  assert.match(css, /\.ledger-card-media-track\s*{[^}]*scroll-snap-type:\s*x mandatory;/s);
  assert.match(css, /\.ledger-card-media-carousel \.ledger-card-media-track\s*{[^}]*scrollbar-width:\s*none;/s);
  assert.match(css, /\.ledger-card-media-slide\s*{[^}]*grid-template-rows:\s*minmax\(0, 1fr\) auto;[^}]*overflow:\s*hidden;/s);
  assert.match(css, /\.ledger-card-media-image\s*{[^}]*width:\s*var\(--ledger-card-media-contained-width, auto\);[^}]*height:\s*var\(--ledger-card-media-contained-height, auto\);[^}]*max-width:\s*100%;[^}]*max-height:\s*100%;[^}]*object-fit:\s*contain;[^}]*object-position:\s*center;/s);
  assert.match(css, /\.ledger-card-media-title\s*{[^}]*display:\s*block;[^}]*width:\s*100%;[^}]*overflow-wrap:\s*anywhere;/s);
  assert.doesNotMatch(css, /\.ledger-card-media-shell:hover \.ledger-card-media-title/);
  assert.match(css, /\.ledger-card-media-progress\s*{[^}]*right:\s*28px;[^}]*bottom:\s*7px;[^}]*left:\s*8px;/s);
  assert.match(css, /\.ledger-card-media-progress-thumb\s*{[^}]*left:\s*var\(--ledger-card-media-slider-thumb-left, 0%\);[^}]*width:\s*var\(--ledger-card-media-slider-thumb-width, 100%\);/s);
  assert.match(css, /\.ledger-card-inline-image-frame\s*{[^}]*aspect-ratio:\s*var\(--ledger-card-inline-image-aspect-ratio, 3 \/ 2\);[^}]*resize:\s*horizontal;/s);
  assert.match(css, /\.ledger-card-inline-image\s*{[^}]*object-fit:\s*contain;/s);
});
