const runtimeDocument = globalThis.document;

export const canvas = runtimeDocument?.querySelector('.canvas') as HTMLElement;
export const content = runtimeDocument?.querySelector('.canvas-content') as HTMLElement;
export const mediaOverlay = runtimeDocument?.querySelector('.canvas-media-overlay') as HTMLElement;
export const controlOverlay = runtimeDocument?.querySelector('.canvas-control-overlay') as HTMLElement;
export const telemetryList = runtimeDocument?.querySelector('.telemetry-list') as HTMLOListElement;
export const modal = runtimeDocument?.querySelector('.confirm-modal') as HTMLDialogElement;
export const shortcutModal = runtimeDocument?.querySelector('.shortcut-modal') as HTMLDialogElement;
export const runbookModal = runtimeDocument?.querySelector('.runbook-modal') as HTMLDialogElement;
export const processModal = runtimeDocument?.querySelector('.process-modal') as HTMLDialogElement;
export const skillModal = processModal;
export const pipelinesModal = runtimeDocument?.querySelector('.pipelines-modal') as HTMLDialogElement;
export const pipelineEditorModal = runtimeDocument?.querySelector('.pipeline-editor-modal') as HTMLDialogElement;
export const pipelineSkillPickerModal = runtimeDocument?.querySelector('.pipeline-skill-picker-modal') as HTMLDialogElement;
export const skillLibraryEditorModal = runtimeDocument?.querySelector('.skill-library-editor-modal') as HTMLDialogElement;
export const projectSettingsModal = runtimeDocument?.querySelector('.project-settings-modal') as HTMLDialogElement;
export const projectColorPickerModal = runtimeDocument?.querySelector('.project-color-picker-modal') as HTMLDialogElement;
export const SVG_NS = 'http://www.w3.org/2000/svg';
